### PR TITLE
update badges

### PR DESCRIPTION
**Pull request by Rexogamer**

### CODE REVIEW

**Comment by Oxygemo** [comment]
Didn't think about that, thanks

**Comment by Rexogamer** [comment]
- thanks

- closes without merge

**Comment by Oxygemo** [comment]
yes that's the joke

**Comment by Rexogamer** [comment]
I guess you did commit it but in that case why not just merge lmao, I don't quite get the joke

**Comment by Oxygemo** [comment]
bcz yes

**Pull request closed without merging**
